language: java
addons:
  sonarcloud:
    organization: "marinakrivonosova"
    token:
      secure:   $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marinakrivonosova_diaryk
