language: java
addons:
  sonarcloud:
    organization: "marinakrivonosova"
   
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marinakrivonosova_diary
