
addons:
  sonarcloud:
    organization: "marinakrivonosova"
    token:
      secure: $SONAR_TOKEN
language: java
jdk: openjdk11
script:
- mvn package -DskipTests
- mvn install sonar:sonar -Ptravis -Dmaven.javadoc.skip=true -B -V
./build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
