language: java
addons:
  sonarcloud:
    organization: "marinakrivonosova"
    token:
      secure: 6bcb7c0e0e9b9ce4b4af8ca9fc96ffdc84de43cb

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=marinakrivonosova_diary
